/**
 * Simulates an API call for user login.
 * This function mimics a real authentication endpoint for development/testing purposes.
 *
 * @param email - The user's email address.
 * @param password - The user's password.
 * @returns Promise<{ success: boolean; message: string; token?: string }>
 */
export async function simulateLoginApi(
  email: string,
  password: string
): Promise<{ success: boolean; message: string; token?: string }> {
  // Simulate network latency for a more realistic UX
  await new Promise((resolve) => setTimeout(resolve, 1200));

  // Hardcoded credentials for simulation
  const validEmail = "admin@gmail.com";
  const validPassword = "Admin123%";

  if (email === validEmail && password === validPassword) {
    // In a real app, the token would be generated by the backend
    const fakeToken = "fake-jwt-token-123456";
    return {
      success: true,
      message: "تم تسجيل الدخول بنجاح",
      token: fakeToken,
    };
  }

  return {
    success: false,
    message: "البريد الإلكتروني أو كلمة المرور غير صحيحة",
  };
}
